export const supplierNames: Record<string, string> = {
  cocojojo: "COCOJOJO",
  redox: "Redox",
  barentz: "Barentz",
  chempoint: "ChemPoint",
  univar: "Univar Solutions",
  brenntag: "Brenntag",
  azelis: "Azelis Personal Care",
  imcd: "IMCD",
  croda: "Croda Beauty",
  knowde: "Knowde",
  "new-directions-aromatics": "New Directions Aromatics",
  "ingredients-online": "Ingredients Online",
  basf: "BASF Personal Care",
  makingcosmetics: "MakingCosmetics",
  lotioncrafter: "Lotioncrafter",
  gutins: "GUTINS",
  parchem: "Parchem",
  rawsource: "RawSource",
  jungbunzlauer: "Jungbunzlauer",
  phibrochem: "PhibroChem",
  "unilong-industry": "Unilong Industry",
  "quzhou-ebright-chemicals": "Quzhou Ebright Chemicals",
  "yuanlian-chemical": "Yuanlian Chemical",
  "independent-chemical-corporation": "Independent Chemical Corporation",
  "green-stone-swiss": "Green Stone Swiss",
  "aogebio-cosmetic": "Aogebio Cosmetic",
  chemotto: "ChemOtto",
  "california-chemical": "California Chemical",
};
export const sourceName = (id: string) => supplierNames[id] || "Supplier reference";
export const isReference = (id: string) => id !== "cocojojo";
