import '@/styles/storefront-styles';
import { OceanShell } from '@/components/ocean/OceanShell';
import { CategoryNavigation } from '@/components/ocean/motion/category-navigation';
import { GlossMotion } from '@/components/ocean/motion/gloss-experience';
import { VisitorTracker } from '@/components/commerce/VisitorTracker';
import { ConsentNotice } from '@/components/scientific/ConsentNotice';
import { SCI_FONT_VARS } from '@/lib/fonts';

/**
 * The storefront, in the COCOJOJO ocean design (IT handoff 2026-10-09).
 *
 * `ocean` is the scope the reference stylesheet hangs off (src/styles/ocean.css,
 * generated by scripts/build-ocean-css.cjs): every rule is prefixed with it, so
 * the design applies here and nowhere else — the admin dashboard, which shares
 * the root layout, is untouched. `gloss-theme` stays on the same element: the
 * reference's own theme layer is keyed to it, as are our add-on styles for
 * the cart groups, quote pages and account (gloss-workspace / gloss-account).
 */
export default function StorefrontLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${SCI_FONT_VARS} ocean gloss-theme antialiased`}>
      <VisitorTracker />
      <CategoryNavigation>
        <OceanShell>{children}</OceanShell>
      </CategoryNavigation>
      <GlossMotion />
      <ConsentNotice />
    </div>
  );
}
